[package]
name = "HelloWorldRustWasmTemplate"
version = "0.1.0"
authors = ["Danielle Melvin <9958611+DanielleJude@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
